version: '3'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: git
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
