version: '3'

services:
  app:
    build: .
    container_name: container_app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: git
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
